### PR TITLE
fix: compare options not passed to check element in storybook runner

### LINKED ISSUE #791: Storybook Runner - Not passing `compareOptions` to the tests
**Environment (please complete the following information):**
 - Node.js version: 20.17.0
 - Yarn version: 4.4.0
 - Browser name and version: Chrome
 - Platform name and version: Mac
 - WebdriverIO version: 9.10.1
 - `@wdio/visual-service` version: 6.3.4

**Config of WebdriverIO + `@wdio/visual-service`**
```js
exports.config = {
  runner: "local",
  specs: [],
  exclude: [],
  capabilities: [],
  logLevel: "error",
  bail: 0,
  services: [
    [
      "visual",
      {
        formatImageName: "{tag}-{browserName}-dpr-{dpr}",
        autoElementScroll: false,
        autoSaveBaseline: false,
        baselineFolder: path.join("storybook-visual-tests/", `storybookTestBaseline/${themeId}/`),
        disableBlinkingCursor: true,
        disableCSSAnimation: true,
        savePerInstance: true,
        screenshotPath: "storybook-visual-tests/",
        waitForFontsLoaded: true,
        compareOptions: {
          ignoreNothing: true,
          ignoreAntialiasing: true,
        },
        storybook: {
          url: baseUrlDomain,
          numShards: 10,
        },
      },
    ],
  ],
  framework: "mocha",
  reporters: ["spec"],
  maxInstances: 10,
  hostname: process.env.SELENIUM_HOST,
  port: process.env.SELENIUM_PORT,
  path: "/wd/hub",
};

```

**Describe the bug**
I noticed the method compare options from wdio config are ignored in the Storybook tests when running in Storybook mode.

**To Reproduce**

Add any `compareOptions` that you know would work in a regular visual test and analyse the result.
Or see below the logs.

**Expected behavior**
I expect that the service compare options would be passed in the Storybook tests.

**Log**

I added a:
```js
throw new Error(JSON.stringify({compareOptions, checkElementOptions, executeCompareOptions}));
```
in checkWebElement to check what was really passed into the `executeImageCompare`
and got the following results (with comments):
```js
{
  compareOptions: {
    returnAllCompareData: true
  },
  checkElementOptions: {
    wic: {
      addressBarShadowPadding: 6,
      autoElementScroll: false,
      addIOSBezelCorners: false,
      autoSaveBaseline: false,
      clearFolder: false,
      formatImageName: "{tag}-{browserName}-dpr-{dpr}",
      isHybridApp: false,
      savePerInstance: true,
      toolBarShadowPadding: 6,
      disableBlinkingCursor: true,
      disableCSSAnimation: true,
      enableLayoutTesting: false,
      fullPageScrollTimeout: 1500,
      hideScrollBars: false,
      waitForFontsLoaded: true,
      compareOptions: {
        blockOutSideBar: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        createJsonReportFiles: false,
        diffPixelBoundingBoxProximity: 5,
        ignoreAlpha: false,
        ignoreAntialiasing: false,
        ignoreColors: false,
        ignoreLess: false,
        ignoreNothing: false,
        rawMisMatchPercentage: false,
        returnAllCompareData: false,
        saveAboveTolerance: 0,
        scaleImagesToSameSize: false
      },
      tabbableOptions: {
        circle: {
          backgroundColor: "#ff0000",
          borderColor: "#000",
          borderWidth: 1,
          fontColor: "#fff",
          fontFamily: "Arial",
          fontSize: 10,
          size: 10,
          showNumber: true
        },
        line: {
          color: "#000",
          width: 1
        }
      }
    },
    method: { // What comes from the Storybook Runner
      baselineFolder: "storybook-visual-tests/baselines/components/mycomponent", // Only this is really passed
      returnAllCompareData: true
    }
  },
  executeCompareOptions: { // What is really passed to the `executeImageCompare()` 
    devicePixelRatio: 3,
    compareOptions: { // What is relevant for the `compareImages()` in `executeImageCompare()` 
      wic: {
        blockOutSideBar: false,
        blockOutStatusBar: false,
        blockOutToolBar: false,
        createJsonReportFiles: false,
        diffPixelBoundingBoxProximity: 5,
        ignoreAlpha: false,
        ignoreAntialiasing: false,
        ignoreColors: false,
        ignoreLess: false,
        ignoreNothing: false,
        rawMisMatchPercentage: false,
        returnAllCompareData: false,
        saveAboveTolerance: 0,
        scaleImagesToSameSize: false
      },
      method: { // Here nothing is passed - No `ignoreLess` etc
        returnAllCompareData: true
      }
    },
    fileName: "components-mycomponent-mystory-element-chrome-dpr-3.png",
    folderOptions: {
      autoSaveBaseline: false,
      actualFolder: "storybook-visual-tests/actual/components/mycomponent",
      baselineFolder: "storybook-visual-tests/storybookTestBaseline/MyTheme/",
      diffFolder: "storybook-visual-tests/diff",
      browserName: "chrome",
      deviceName: "not_known",
      isMobile: false,
      savePerInstance: true
    },
    isAndroidNativeWebScreenshot: false,
    isHybridApp: false,
    isLandscape: false,
    platformName: "linux"
  }
}
```

### PR DESCRIPTION
**Pull request by alcpereira**
Fixes #791

### CODE REVIEW

File: packages/visual-service/src/storybook/launcher.ts [hunk 1]
```diff
@@ -52,6 +52,22 @@ export default class VisualLauncher extends BaseClass  {
...
+                blockOutToolBar: this.#options.blockOutToolBar,
+                ignoreAlpha: this.#options.ignoreAlpha,
+                ignoreAntialiasing: this.#options.ignoreAntialiasing,
+                ignoreColors: this.#options.ignoreColors,
+                ignoreLess: this.#options.ignoreLess,
+                ignoreNothing: this.#options.ignoreNothing,
+                rawMisMatchPercentage: this.#options.rawMisMatchPercentage,
+                returnAllCompareData: this.#options.returnAllCompareData,
+                saveAboveTolerance: this.#options.saveAboveTolerance,
+                scaleImagesToSameSize: this.#options.scaleImagesToSameSize,
```
Comment (wswebcreation) [inline packages/visual-service/src/storybook/launcher.ts:68]: Can we deconstruct? feels more "readable" and less duplication. WDYT?

**Review by wswebcreation — COMMENTED** [review]
Thanks, this looks great, just one minor thing

File: packages/visual-service/src/storybook/launcher.ts (hunk 1 above)
Comment (alcpereira) [reply packages/visual-service/src/storybook/launcher.ts:68]: The only other option is:

```js
const {
    blockOutSideBar,
    blockOutStatusBar,
    blockOutToolBar,
    ignoreAlpha,
    ignoreAntialiasing,
    ignoreColors,
    ignoreLess,
    ignoreNothing,
    rawMisMatchPercentage,
    returnAllCompareData,
    saveAboveTolerance,
    scaleImagesToSameSize,
} = this.#options;

const compareOptions: CheckElementMethodOptions = {
    blockOutSideBar,
    blockOutStatusBar,
    blockOutToolBar,
    ignoreAlpha,
    ignoreAntialiasing,
    ignoreColors,
    ignoreLess,
    ignoreNothing,
    rawMisMatchPercentage,
    returnAllCompareData,
    saveAboveTolerance,
    scaleImagesToSameSize,
};
```
Which is a bit more verbose.

Another option would be to move it to another function like the `scanStorybook(config, this.#options)`

I'm fine with both, let me know which one you prefer (actual, destructured, or separate function)

Comment (wswebcreation) [reply packages/visual-service/src/storybook/launcher.ts:68]: ok, let's keep it like this 😆
